version: '1.0.{build}'

platform:
  - x64

cache:
  - node_modules -> package.json
  - app\node_modules -> package.json
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: Mcr1WaCcl8T8zMHQONttCUUyYfd4jtEnMjnWlE7vCzBf6tqq+X3LHPMzSWSw+UTU

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install npm@4 -g
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm test
  - npm run dist

test: off
